### ISSUE TITLE
Is there a way to generate the mesh of the trained scene?

### ISSUE THREAD

**Issue by WXuanyang** [weiyithu/NerfingMVS#18]
I'm wondering if there's a option or script in your code to generate the 3D mesh of the trained scene? There's such option in the nerf-pytorch, but your code seems to be based on a older version of nerf-pytorch. And it will be great if you can also explain how to generate images from a specific view, like from an unseen direction. Many thanks

**Comment by weiyithu** [comment]
Sorry, we do not provide mesh generation scripts since we need depth priors for each view. You may fuse multi-view depths and use delaunay_mesher in COLMAP to generate mesh. As mentioned in our paper (Section 3.4), for the unseen views, we currently adopt the depth priors of neighbor view. However, this is an approxiamtion and we believe there exists better solutions.

**Comment by WXuanyang** [comment]
Thanks! That was really helpful
